version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: song-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=songdb

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: song-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/songdb
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - ./apps/backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: song-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
